version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    # ports:
    #   - 53615:11434

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    restart: unless-stopped
    volumes:
      - ollama-ui-data:/app/backend/data
    ports:
      - 53616:8080
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api

volumes:
  ollama-data:
  ollama-ui-data:
